# NOTE
# This script can be optimized further in terms of speed of execution, readability etc.

name: Build, Push, Deploy

on:
  push:
    branches:    
      - master

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set AWS cli credentials to be used with following steps
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push docker image
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: lok-dev-ngs
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker images
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest  

      - id: modified
        uses: pheel/path-watcher-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: '.github/workflows/codedeploy/lambda/**/*'

      # Building and pushing CodeDeploy helper lambda functions
      # This step will run only in case lambda paths are changed
      - name: Build and push CodeDeploy lambdas
        if: steps.modified.outputs.modified
        run: |
          cd .github/workflows/codedeploy/lambda/AfterAllowTestTraffic
          python -m pip install -r requirements.txt -t .
          zip -rq ./lambda.zip ./
          aws lambda update-function-code --function-name lok-dev-ngs-deploy-after-allow-test-traffic \
                                          --zip-file fileb://lambda.zip

          cd $GITHUB_WORKSPACE && cd .github/workflows/codedeploy/lambda/AfterAllowTraffic
          python -m pip install -r requirements.txt -t .
          zip -rq ./lambda.zip ./
          aws lambda update-function-code --function-name lok-dev-ngs-deploy-after-allow-traffic \
                                          --zip-file fileb://lambda.zip


  Deploy:
    needs: [ BuildAndPush ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set AWS cli credentials to be used with following steps
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Create and initiate a deployment in CodeDeploy
      - name: Deploy
        run: |
          cd .github/workflows/codedeploy
          aws s3 cp appspec.yaml s3://lok-dev-appspec/ngs/appspec.yaml
          aws deploy create-deployment --cli-input-json file://create-deployment.json
      
      - name: Deployment status URL
        run: |
          echo "Please visit CodeDeploy console for the deployment status:"
          echo "https://console.aws.amazon.com/codesuite/codedeploy/deployments?region=$AWS_REGION" 